services:
  webserver:
    # build: CV/static
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../app:/app
    ports:
      - "80:80"
    #extra_hosts:
    #- "zozotest:127.0.0.1"

  app:
    build: services/php
    volumes:
      - ../app:/app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./public/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}

networks:
  app-network: {}